# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Pipeline CI

on:
  push:
    branches:
    - master
    - next

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    
      # Configure Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '17'
          
      # Install npm modules
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0
        with:
          useLockFile: true
        
      # Attempt to build
      - name: Build
        run: |
          npm run build
       
      # Get build output
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: './public_html'
          
